from __future__ import annotations

import base64
import re
import uuid as _uuid_mod

import vobject

from .model import Address, Card, NameComponents, Related, TypedValue

# ── UID normalisation ─────────────────────────────────────────────────────────

# Patterns that identify vendor-generated UIDs that should be replaced
_VENDOR_UID_PATTERNS = (
    re.compile(r"^proton-", re.I),
    re.compile(r"^proton_", re.I),
    re.compile(r"ab[0-9a-f]{8}-", re.I),          # Apple AddressBook: ABxxxx-
    re.compile(r"^X-APPLE", re.I),
    re.compile(r"@gmail\.com$", re.I),              # Google uses email as UID
    re.compile(r"@googlemail\.com$", re.I),
    re.compile(r"outlook\.", re.I),
    re.compile(r"live\.com", re.I),
    re.compile(r"apple\.com", re.I),
    re.compile(r"icloud\.com", re.I),
    re.compile(r"protonmail\.", re.I),
    re.compile(r"^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
               re.I),   # bare RFC urn:uuid — keep as-is (already canonical)
)

# The last pattern above is a *keep* pattern — we only replace if NOT matching it
_CANONICAL_UID = re.compile(
    r"^(urn:uuid:)?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.I,
)
# vCard Studio-issued UIDs always start with this prefix
_VS_PREFIX = "vcard-studio-"


def _is_vendor_uid(uid: str) -> bool:
    """Return True if the UID looks like it was generated by a third-party vendor."""
    if not uid:
        return True
    # Already a clean vCard Studio UID — keep it
    if uid.startswith(_VS_PREFIX):
        return False
    # A bare RFC 4122 UUID with no vendor fingerprint — keep it
    if _CANONICAL_UID.match(uid):
        return False
    # Anything else (proton-web-xxx, apple ABxxx, google email UIDs, etc.) — replace
    return True


def new_vs_uid() -> str:
    """Generate a new vCard Studio UID: vcard-studio-<uuid4>"""
    return f"{_VS_PREFIX}{_uuid_mod.uuid4()}"


_PHOTO_PROPS = frozenset({"PHOTO", "LOGO", "SOUND"})


def _get_text(v, default=None):
    try:
        return str(v.value).strip()
    except Exception:
        return default


def _param_values(prop, name: str) -> list[str]:
    """Return a parameter as a flat string list, case-insensitively."""
    try:
        params = getattr(prop, "params", {}) or {}
        raw = next((v for k, v in params.items() if str(k).upper() == name.upper()), None)
        if raw is None:
            return []
        if isinstance(raw, (list, tuple)):
            return [str(v) for v in raw]
        return [str(raw)]
    except Exception:
        return []


def _decode_b64_param(prop, name: str) -> str:
    values = _param_values(prop, name)
    if not values:
        return ""
    encoded = values[0].strip()
    try:
        encoded += "=" * (-len(encoded) % 4)
        return base64.urlsafe_b64decode(encoded.encode("ascii")).decode("utf-8").strip()
    except Exception:
        return ""


def _clean_apple_label(label: str) -> str:
    """Turn Apple system-label syntax (_$!<Home>!$_) into display text."""
    label = (label or "").strip()
    match = re.fullmatch(r"_\$!<(.+)>!\$_", label)
    return match.group(1).strip() if match else label


def _is_pref(prop) -> bool:
    values = [v.upper() for v in _param_values(prop, "TYPE")]
    if "PREF" in values:
        return True
    pref = _param_values(prop, "PREF")
    return bool(pref and pref[0] not in {"", "0", "false", "False"})


def _apple_label(prop) -> str:
    label = _decode_b64_param(prop, "X-VCS-APPLE-LABEL-B64")
    if not label:
        stored = _param_values(prop, "X-VCARD-STUDIO-LABEL")
        label = stored[0].strip() if stored else ""
    return _clean_apple_label(label)


def _type_from_apple_label(label: str) -> str:
    """Map common Apple display labels to canonical TYPE values."""
    value = (label or "").strip().casefold()
    if value == "home":
        return "HOME"
    if value == "work":
        return "WORK"
    if value in {"iphone", "mobile", "cell"}:
        return "CELL"
    return ""


def _parse_addresses(vc: vobject.base.Component) -> list[Address]:
    addresses: list[Address] = []
    for adr in getattr(vc, "adr_list", []):
        try:
            val = adr.value
            addresses.append(
                Address(
                    po_box=val.box or None,
                    extended=val.extended or None,
                    street=val.street or None,
                    locality=val.city or None,
                    region=val.region or None,
                    postal_code=val.code or None,
                    country=val.country or None,
                    type=_get_type_param(adr) or _type_from_apple_label(_apple_label(adr)),
                    label=_apple_label(adr),
                    pref=_is_pref(adr),
                    apple_country_code=(
                        _decode_b64_param(adr, "X-VCS-APPLE-ADR-B64")
                        or ((_param_values(adr, "X-VCARD-STUDIO-APPLE-ADR") or [""])[0].strip())
                    ),
                )
            )
        except Exception:
            pass
    return addresses


def _children_named(vc: vobject.base.Component, name: str):
    wanted = name.upper()
    for child in vc.getChildren():
        if getattr(child, "name", "").upper() == wanted:
            yield child


def strip_photos(vc: vobject.base.Component) -> int:
    """Remove any PHOTO/LOGO/SOUND children from the raw vobject. Returns count removed."""
    to_remove = [
        child for child in list(vc.getChildren())
        if getattr(child, "name", "").upper() in _PHOTO_PROPS
    ]
    for child in to_remove:
        vc.remove(child)
    return len(to_remove)


def _get_type_param(prop) -> str:
    """Extract the TYPE parameter (HOME, WORK, CELL, etc.) from a vobject property.

    Returns empty string if no type is set.
    """
    try:
        tp = None
        if hasattr(prop, "type_param"):
            tp = prop.type_param
        elif hasattr(prop, "params"):
            tp = prop.params.get("TYPE", None)
        if tp is None:
            return ""
        if isinstance(tp, list):
            # vobject may return list — take first meaningful value
            for v in tp:
                s = str(v).upper().strip()
                if s and s not in ("INTERNET", "PREF", "X400"):
                    return s
            return ""
        s = str(tp).upper().strip()
        return s if s not in ("INTERNET", "PREF", "X400") else ""
    except Exception:
        return ""


def normalize_cards(
    vcards: list[tuple[vobject.base.Component, str]],
) -> list[Card]:
    """Convert (vobject_component, source_label) pairs into Card objects.

    Strips photos immediately and records the source filename on each card
    so the report can show where each contact came from.
    """
    out: list[Card] = []
    for vc, source_label in vcards:
        fn = _get_text(getattr(vc, "fn", None))

        # Parse structured N field into NameComponents
        name = NameComponents()
        if getattr(vc, "n", None):
            try:
                nval = vc.n.value
                # vobject gives us a Name object with attributes
                name.family     = (nval.family     or "").strip()
                name.given      = (nval.given      or "").strip()
                name.additional = (nval.additional or "").strip()
                name.prefix     = (nval.prefix     or "").strip()
                name.suffix     = (nval.suffix     or "").strip()
            except Exception:
                # Fallback: parse raw string
                raw = _get_text(getattr(vc, "n", None)) or ""
                if raw:
                    name = NameComponents.from_vcard_str(raw)

        emails: list[str] = []
        typed_emails: list[TypedValue] = []
        for e in getattr(vc, "email_list", []):
            val = _get_text(e)
            if val:
                val = val.lower()
                emails.append(val)
                label = _apple_label(e)
                etype = _get_type_param(e) or _type_from_apple_label(label)
                typed_emails.append(
                    TypedValue(value=val, type=etype, label=label, pref=_is_pref(e))
                )

        tels: list[str] = []
        typed_tels: list[TypedValue] = []
        for t in getattr(vc, "tel_list", []):
            val = re.sub(r"\s+", "", _get_text(t, ""))
            if val:
                tels.append(val)
                ttype = _get_type_param(t)
                label = _apple_label(t)
                # Apple often expresses iPhone/Mobile only through X-ABLabel.
                if not ttype:
                    ttype = _type_from_apple_label(label)
                typed_tels.append(
                    TypedValue(value=val, type=ttype, label=label, pref=_is_pref(t))
                )

        urls: list[TypedValue] = []
        for u in getattr(vc, "url_list", []):
            val = _get_text(u)
            if val:
                urls.append(
                    TypedValue(
                        value=val,
                        type=_get_type_param(u) or _type_from_apple_label(_apple_label(u)),
                        label=_apple_label(u),
                        pref=_is_pref(u),
                    )
                )

        nicknames: list[str] = []
        for nick in getattr(vc, "nickname_list", []):
            try:
                value = nick.value
                if isinstance(value, (list, tuple)):
                    nicknames.extend(str(v).strip() for v in value if str(v).strip())
                else:
                    nicknames.extend(v.strip() for v in str(value).split(",") if v.strip())
            except Exception:
                pass
        nicknames = list(dict.fromkeys(nicknames))

        org = None
        if getattr(vc, "org", None):
            try:
                org = " ".join([p for p in vc.org.value if p]).strip()
            except Exception:
                pass

        title = _get_text(getattr(vc, "title", None))
        bday = _get_text(getattr(vc, "bday", None))
        anniversary = _get_text(getattr(vc, "anniversary", None))
        if not anniversary:
            for date_prop in _children_named(vc, "X-ABDATE"):
                label = _apple_label(date_prop).casefold()
                value = _get_text(date_prop)
                if value and (not label or label == "anniversary"):
                    anniversary = value
                    break

        uid = _get_text(getattr(vc, "uid", None))
        old_uid: str | None = None
        external_uids: list[str] = []
        for prop in list(_children_named(vc, "X-VCARD-STUDIO-EXTERNAL-UID")) + list(_children_named(vc, "X-ABUID")):
            value = _get_text(prop)
            if value and value not in external_uids:
                external_uids.append(value)

        # vCard Studio owns the canonical UID.  Vendor UIDs are retained as
        # aliases so a future iCloud/provider export can still match safely.
        if _is_vendor_uid(uid or ""):
            old_uid = uid
            if old_uid and old_uid not in external_uids:
                external_uids.append(old_uid)
            uid = new_vs_uid()

        rev = _get_text(getattr(vc, "rev", None))
        addresses = _parse_addresses(vc)

        # Parse RELATED (vCard 4.0) — links to other contacts
        related: list[Related] = []
        for rel_prop in getattr(vc, "related_list", []):
            try:
                # type_param may be a string, a list, or absent depending on vobject version
                rel_type = "contact"
                tp = None
                if hasattr(rel_prop, "type_param"):
                    tp = rel_prop.type_param
                elif hasattr(rel_prop, "params"):
                    tp = rel_prop.params.get("TYPE", None)
                if tp is not None:
                    if isinstance(tp, list):
                        rel_type = str(tp[0]).lower().strip() if tp else "contact"
                    else:
                        rel_type = str(tp).lower().strip()
                val = str(rel_prop.value).strip()
                if val.startswith("urn:uuid:"):
                    related.append(Related(rel_type=rel_type, uid=val[9:]))
                elif val:
                    related.append(Related(rel_type=rel_type, text=val))
            except Exception:
                pass

        # Apple vCard 3.0 related-name properties (spouse/parent/etc.).
        for rel_prop in _children_named(vc, "X-ABRELATEDNAMES"):
            value = _get_text(rel_prop)
            if not value:
                continue
            rel_type = (_apple_label(rel_prop) or "contact").strip().lower()
            if not any(r.text == value and r.rel_type == rel_type for r in related):
                related.append(Related(rel_type=rel_type, text=value))

        # Parse MEMBER (RFC 6350, valid for KIND=group) plus the vCard Studio
        # preservation property used for legacy organisation membership.
        member: list[str] = []
        for member_prop in list(getattr(vc, "member_list", [])) + list(_children_named(vc, "X-VCARD-STUDIO-MEMBER")):
            try:
                value = str(member_prop.value).strip()
                if value.startswith("urn:uuid:"):
                    value = value[9:]
                if value and value not in member:
                    member.append(value)
            except Exception:
                pass

        # Parse CATEGORIES — may be a list (vCard 4.0) or a comma-separated string
        categories: list[str] = []
        for cat_prop in getattr(vc, "categories_list", []):
            try:
                val = cat_prop.value
                if isinstance(val, (list, tuple)):
                    categories.extend(v.strip() for v in val if v.strip())
                elif isinstance(val, str):
                    categories.extend(v.strip() for v in val.split(",") if v.strip())
            except Exception:
                pass
        categories = sorted(set(categories))

        photo_count = strip_photos(vc)

        note = _get_text(getattr(vc, "note", None))

        # ── Parse [vCS: ...] block written by Apple-compat export ─────────────
        # When exporting for Apple/iOS, vCard Studio preserves 4.0-only fields
        # in the NOTE as a compact inline block:
        #   [vCS: GENDER: M | CATEGORIES: Army, Friends | KIND: self | ...]
        # On re-import we parse this back into the correct structured fields
        # and strip the block from the visible note text.
        _vcs_gender: str | None = None
        _vcs_kind: str | None = None
        _vcs_categories: list[str] = []
        _vcs_anniversary: str | None = None
        _vcs_related: list[Related] = []
        _vcs_member: list[str] = []

        # Two on-disk formats exist:
        #   current : "[vCS: KEY: val | KEY: val]" (single line)
        #   legacy  : "\n\n---vCard Studio---\nKEY: val\nKEY: val" (written by
        #             older Apple exports, e.g. cards-out/apple-2026-05-10-*)
        _vcs_pairs: list[str] = []
        if note and "[vCS:" in note:
            # Pattern allows inner [...] pairs (e.g. RELATED[spouse])
            _vcs_match = re.search(r"\[vCS:\s*((?:[^\[\]]|\[[^\[\]]*\])*)\]", note)
            if _vcs_match:
                _vcs_pairs.extend(_vcs_match.group(1).split("|"))
                note = re.sub(r"\s*\[vCS:(?:[^\[\]]|\[[^\[\]]*\])*\]", "", note).strip() or None
        if note and "---vCard Studio---" in note:
            _visible, _, _legacy = note.partition("---vCard Studio---")
            _vcs_pairs.extend(line for line in _legacy.splitlines() if line.strip())
            note = _visible.strip() or None
        for _pair in _vcs_pairs:
            _pair = _pair.strip()
            if ":" not in _pair:
                continue
            _key, _, _val = _pair.partition(":")
            _key = _key.strip().upper()
            _val = _val.strip()
            if _key == "GENDER":
                _vcs_gender = _val.upper() or None
            elif _key == "KIND":
                _vcs_kind = _val.lower() or None
            elif _key == "CATEGORIES":
                _vcs_categories = [c.strip() for c in _val.split(",") if c.strip()]
            elif _key == "ANNIVERSARY":
                _vcs_anniversary = _val or None
            elif _key.startswith("RELATED"):
                # RELATED[spouse]: uid-or-text
                _rtype_match = re.match(r"RELATED\[([^\]]+)\]", _key)
                _rtype = _rtype_match.group(1).lower() if _rtype_match else "contact"
                if _val.startswith("urn:uuid:"):
                    _vcs_related.append(Related(rel_type=_rtype, uid=_val[9:]))
                elif _val.startswith("vcard-studio-") or (
                    len(_val) == 36 and _val.count("-") == 4
                ):
                    _vcs_related.append(Related(rel_type=_rtype, uid=_val))
                elif _val:
                    _vcs_related.append(Related(rel_type=_rtype, text=_val))
            elif _key == "MEMBER":
                _member = _val[9:] if _val.startswith("urn:uuid:") else _val
                if _member:
                    _vcs_member.append(_member)

        # Parse X-VCARD-STUDIO-WAIVED — "not required" field markers
        # vobject stores X- properties with hyphens converted to underscores
        waived_raw = _get_text(getattr(vc, "x_vcard_studio_waived", None))
        waived: set = set()
        if waived_raw:
            waived = {f.strip() for f in waived_raw.split(",") if f.strip()}

        # Parse KIND (vCard 4.0) — critical for preserving user-set org/individual/self
        kind: str | None = None
        kind_raw = _get_text(getattr(vc, "kind", None))
        if kind_raw:
            kind = kind_raw.strip().lower()
        studio_kind = _get_text(getattr(vc, "x_vcard_studio_kind", None))
        if studio_kind:
            kind = studio_kind.strip().lower()

        # Apple vCard 3.0 uses X-ABShowAs for company/profile semantics.
        apple_show_as = _get_text(getattr(vc, "x_abshowas", None))
        if apple_show_as and not kind:
            show = apple_show_as.strip().upper()
            if show == "COMPANY":
                kind = "org"
            elif show == "PROFILE":
                kind = "self"

        # Parse GENDER (vCard 4.0) — M|F|O|N|U
        gender: str | None = None
        gender_raw = _get_text(getattr(vc, "gender", None))
        if gender_raw:
            gender = gender_raw.strip().upper().split(";")[0]  # "M;Male" → "M"

        # Parse X-IOS-GIVEN / X-IOS-FAMILY — non-destructive iOS display name override
        # vobject converts hyphens to underscores in attribute names
        x_ios_given  = _get_text(getattr(vc, "x_ios_given",  None)) or None
        x_ios_family = _get_text(getattr(vc, "x_ios_family", None)) or None

        # Apply vCS-recovered fields — only fill gaps, never overwrite existing values
        if _vcs_gender and not gender:
            gender = _vcs_gender
        if _vcs_kind and not kind:
            kind = _vcs_kind
        if _vcs_anniversary and not anniversary:
            anniversary = _vcs_anniversary
        if _vcs_categories:
            # Merge — add any categories from the vCS block not already present
            categories = sorted(set(categories) | set(_vcs_categories))
        if _vcs_related:
            # Append recovered relationships not already in related list
            existing_uids = {r.uid for r in related if r.uid}
            for r in _vcs_related:
                if r.uid and r.uid not in existing_uids:
                    related.append(r)
                    existing_uids.add(r.uid)
                elif not r.uid and not any(
                    x.text == r.text and x.rel_type == r.rel_type for x in related
                ):
                    related.append(r)
        for _member in _vcs_member:
            if _member not in member:
                member.append(_member)

        card = Card(
            raw=vc,
            fn=fn,
            name=name,
            emails=emails,
            tels=tels,
            typed_emails=typed_emails,
            typed_tels=typed_tels,
            urls=urls,
            nicknames=nicknames,
            org=org,
            title=title,
            bday=bday,
            anniversary=anniversary,
            uid=uid,
            external_uids=external_uids,
            rev=rev,
            addresses=addresses,
            categories=categories,
            related=related,
            member=member,
            note=note,
            kind=kind,
            gender=gender,
            x_ios_given=x_ios_given,
            x_ios_family=x_ios_family,
            _source_files=[source_label],
        )
        # Restore "not required" field markers (persisted as X-VCARD-STUDIO-WAIVED)
        if waived:
            card._waived = waived
        if photo_count:
            card.log_change(f"Stripped {photo_count} photo/logo/sound property(ies)")
        if old_uid:
            card.log_change(f"Vendor UID retained as alias: {old_uid} → canonical {uid}")

        # Round trips via other address books leave duplicates that differ only
        # invisibly (bidi marks, NBSP, formatting) — collapse them on every load.
        from .merge import dedupe_card_fields
        dedupe_card_fields(card)

        out.append(card)
    return out


def strip_proprietary(card: Card) -> Card:
    from .proprietary import DefaultStripper
    return DefaultStripper().strip(card)
